name: Bench

on: [push]

jobs:
  traanslate:
    name: Bench
    runs-on: ubuntu-latest
    environment: meta-tracing-environment
    container:  
      image: iamkimchi/pypy-trace:latest
    steps:
    - uses: actions/checkout@v3
    - name: Download PyPy
      run: make get-pypy
    - name: lfs install
      run: git lfs install
    - name: lfs pull
      run: git lfs pull
    - name: Bench 0.0.9
      run: bash ./scripts/bench.sh 0.0.9 100 100
    - name: Bench 0.0.10
      run: bash ./scripts/bench.sh 0.0.10 100 100
    - name: Bench 0.0.11
      run: bash ./scripts/bench.sh 0.0.11 100 100