name: PyTest 

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: meta-tracing
        environment-file: environment.yml
        python-version: 2.7.18
        auto-activate-base: false
    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: pip install -r ./requirements.txt
    - name: Lint
      run: make lint-check
    - name: Install Mercurial
      run: sudo apt-get install mercurial
    - name: Download RPython
      run: hg clone https://foss.heptapod.net/pypy/pypy .pypy
    - name: Test with pytest
      run: source .envrc && make test
  
  rpython-no-jit:
    name: PYPY translate (no jit)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: meta-tracing
        environment-file: environment.yml
        python-version: 2.7.18
        auto-activate-base: false
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install Mercurial
      run: sudo apt-get install mercurial
    - name: Download RPython
      run: hg clone https://foss.heptapod.net/pypy/pypy .pypy
    - name: RPython Translate
      run: make translate-awk-vm-no-jit
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: awk_vm-c-no-jit
        path: ./awk_vm-c